# brew bundle Brewfile

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'asdf'
brew 'coreutils'
brew 'fzf'
brew 'gawk'
brew 'git'
brew 'gpg'
brew 'htop'
brew 'nvim'
brew 'openssl'
brew 'readline'
brew 'ripgrep'
brew 'tldr'
brew 'wget'

cask 'keepingyouawake'
cask 'kitty'
cask 'ngrok'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'
