" Oldie {
  set nocompatible               " be iMproved
  filetype off                   " required!
  set backspace=indent,eol,start
  set history=5000
  set t_Co=256
  set encoding=utf-8 fileencoding=utf-8
" }

call plug#begin('~/.vim/plugged')

" Plugins {
  " ctrl-p is a fuzzy file finder.
  Plug 'kien/ctrlp.vim'
  " themes
  Plug 'chriskempson/base16-vim'
  " git wrapper
  Plug 'tpope/vim-fugitive'
  " search
  Plug 'rking/ag.vim'
  " snippets
  Plug 'MarcWeber/vim-addon-mw-utils'
  Plug 'tomtom/tlib_vim'
  Plug 'garbas/vim-snipmate'
  Plug 'honza/vim-snippets'
  " surround
  Plug 'tpope/vim-surround'
  " blocks converting (gS gJ)
  Plug 'AndrewRadev/splitjoin.vim'
" }

call plug#end()

" Settings {
  set number relativenumber
  set cursorline

  " disable swap and backup
  set nobackup
  set noswapfile

  " split below/right
  set splitbelow
  set splitright

  let mapleader=','

  syntax on
  filetype on
  filetype plugin on
  filetype indent on
  filetype plugin indent on

  " Indentation
  set expandtab     " all tabs expands to spaces
  set sw=2          " automagic indent width
  set tabstop=2     " size of tab in spaces
  set ts=2          " size of tab
  set shiftround    " round indent to multiple of 'shiftwidth', applies to > and <
  set smarttab
  set softtabstop=2 " number of spaces that a <Tab> counts for
                    " while performing editing operations

  " smartcase -- normally ignores case, but when we type uppercase character
  " in search box it will be CASE SENSITIVE
  set ignorecase
  set smartcase
  set hlsearch

  " statusline
  set laststatus=2
  set statusline=%f\ %m%r%w%y%=:b%n\ 🐘\ \ %l/%L

  " show trailing whitespace
  highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
  autocmd ColorScheme * highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
  match ExtraWhitespace /\s\+$\| \+\ze\t/
" }

" Keybindings {
  " Save file
  nnoremap <Leader>w :w<CR>
  "Copy and paste from system clipboard
  vmap <Leader>y "+y
  nmap <Leader>Y "+Y
  vmap <Leader>d "+d
  nmap <Leader>p "+p
  nmap <Leader>P "+P
  vmap <Leader>p "+p
  vmap <Leader>P "+P

  map <Leader>gs :Gstatus<CR>
  map <Esc><Esc> :noh<CR>

  " Buffers
  nnoremap <Leader>l :ls<CR>
  nnoremap <Leader>b :bp<CR>
  nnoremap <Leader>f :bn<CR>
  nnoremap <Leader>g :e#<CR>
  nnoremap <Leader>1 :1b<CR>
  nnoremap <Leader>2 :2b<CR>
  nnoremap <Leader>3 :3b<CR>
  nnoremap <Leader>4 :4b<CR>
  nnoremap <Leader>5 :5b<CR>
  nnoremap <Leader>6 :6b<CR>
  nnoremap <Leader>7 :7b<CR>
  nnoremap <Leader>8 :8b<CR>
  nnoremap <Leader>9 :9b<CR>
  nnoremap <Leader>0 :10b<CR>

  command WQ wq "Error prone
  command Wq wq
  command Cq cq
  command W w
  command Q q

  command! -range ConvertHashSyntax <line1>,<line2>s/:\(\S\{-}\)\(\s\{-}\)=> /\1:\2/
" }

" Theme {
  if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
  endif
" }
